name: Ollama Gemma Action

on:
  workflow_dispatch:  # 手動実行可能
  push:
    branches: [ main ]
    paths:
      - 'Dockerfile'
      - 'entrypoint.sh'
  pull_request:
    branches: [ main ]

jobs:
  build-and-push:
    runs-on: ubuntu-latest
    # GitHub Container Registry への書き込み権限が必要
    permissions:
      contents: read
      packages: write
    
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
      
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3
      
      - name: Log in to GitHub Container Registry
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}
      
      - name: Extract metadata for Docker
        id: meta
        uses: docker/metadata-action@v5
        with:
          images: ghcr.io/${{ github.repository }}/ollama-gemma
          tags: |
            type=raw,value=latest
            type=sha,format=short
      
      - name: Build and push Docker image
        uses: docker/build-push-action@v5
        with:
          context: .
          push: true
          tags: ${{ steps.meta.outputs.tags }}
          labels: ${{ steps.meta.outputs.labels }}
          cache-from: type=gha
          cache-to: type=gha,mode=max

  run-ollama:
    needs: build-and-push
    runs-on: ubuntu-latest
    
    steps:
      - name: Log in to GitHub Container Registry
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}
      
      - name: Pull and run Ollama container
        run: |
          # 最新のイメージをpull
          docker pull ghcr.io/${{ github.repository }}/ollama-gemma:latest
          
          # コンテナを実行
          echo "Running Ollama container..."
          docker run -d -p 11434:11434 --name ollama-container ghcr.io/${{ github.repository }}/ollama-gemma:latest
          
          # コンテナが起動するまで待機
          echo "Waiting for Ollama to initialize..."
          sleep 15
          
          # Ollama APIが利用可能か確認
          echo "Checking if Ollama API is available:"
          curl -s http://localhost:11434/api/tags
          
          # Gemma-3-4b-itモデルでクエリを実行
          echo "Running query with Gemma-3-4b-it model:"
          curl -s http://localhost:11434/api/generate -d '{
            "model": "gemma3:4b",
            "prompt": "Explain the benefits of using containers in CI/CD pipelines.",
            "stream": false
          }' | jq '.response'
      
      - name: Cleanup
        if: always()
        run: |
          docker stop ollama-container || true
          docker rm ollama-container || true